baseURL = "https://blog.wooseop.kim/"
title = "화무십일홍"
languageCode = "ko"
defaultContentLanguage = "ko"
hasCJKLanguage = true
theme = "terminal"
googleAnalytics = "UA-78757178-3"

[author]
  name = "Wooseop Kim"
  bio = "화무십일홍"
  job = "Student"
  location = "Seoul"
  picture = "/images/avatar.jpg"

[params]
  fullWidthTheme = false
  centerTheme = false
  themeColor = "green"
  favicon = ""

[languages]
  [languages.ko]
    languageName = "한국어"
    menuMore = "더 보기"
    readMore = "더 읽기"
    readOtherPosts = "다른 글 읽기"

  [languages.ko.params.logo]
    logoText = "Wooseop Kim"

  [[languages.ko.menu.main]]
    weight = 1
    name = "Blog"
    url = "/"
  [[languages.ko.menu.main]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/wooseopkim"
  [[languages.ko.menu.main]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/wooseop-kim-870589107/"
  [[languages.ko.menu.main]]
    weight = 4
    name = "Steemit"
    url = "https://steemit.com/@wooseop"
  [[languages.ko.menu.main]]
    weight = 5
    name = "Brunch"
    url = "https://brunch.co.kr/@@tcN"
  [[languages.ko.menu.main]]
    weight = 9
    name = "RSS"
    url = "/index.xml"
